force-app/main/default/objects/Data_Dictionary_Field__c/Data_Dictionary_Field__c.object-meta.xml
<CustomObject>
    <description>Records of individual fields within standard and custom objects, custom settings, custom metadata, etc.</description>
    <label>Data Dictionary Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Is_Dependent_Picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Auto Number</fullName>
            </value>
            <value>
                <fullName>BitVector</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Complex Value</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>External Lookup</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Hierarchy</fullName>
            </value>
            <value>
                <fullName>IP Address</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Master-Detail</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
            </value>
            <value>
                <fullName>Roll-Up Summary</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Data_Type_Details_Trunc__c.field-meta.xml
<CustomField>
    <fullName>Data_Type_Details_Trunc__c</fullName>
    <inlineHelpText>In a few cases, Data Type Details can be very long. This is a shortened (truncated) version, limited to 100 characters, for use in filtering.</inlineHelpText>
    <label>Data Type Details (Trunc)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Data_Dictionary_Object__c</referenceTo>
    <relationshipLabel>Data Dictionary Fields</relationshipLabel>
    <relationshipName>Data_Dictionary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Field</fullName>
            </value>
            <value>
                <fullName>Standard Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Usage_Count__c.field-meta.xml
<CustomField>
    <fullName>Usage_Count__c</fullName>
    <inlineHelpText>A count of how many records have a value (are not empty/null) for this field, as of the last sync. Note that this information can&apos;t be obtained for certain types of fields--for example, a formula field can theoretically have or not have a value depending on the user viewing the record.</inlineHelpText>
    <label>Usage Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Has_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Has_Record_Types__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the object uses Record Types.</inlineHelpText>
    <label>Has Record Types</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Stub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Object</fullName>
            </value>
            <value>
                <fullName>Custom Object</fullName>
            </value>
            <value>
                <fullName>Custom Metadata Type</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Big Object</fullName>
            </value>
            <value>
                <fullName>Platform Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ddFieldDetailsBatch.cls
public with sharing class ddFieldDetailsBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    private String objectDurableId;
    private String objectApiName;
    private String mode;

    public ddFieldDetailsBatch(String mode) {
        this.mode = mode;
    }

    private String getNextObject() {
        String s = '';

        return s;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = '';
        if (this.mode == 'picklists-dependent') {
            query = 'SELECT Id, API_Name__c, Object__r.API_Name__c, Durable_ID__c FROM Data_Dictionary_Field__c WHERE Is_Dependant_Picklist__c = true AND Status__c = \'' + ddCoreService.FIELD_STATUS_ACTIVE + '\' ORDER BY API_Name__c';
        } else if (this.mode == 'picklists-recordtypes') {
            query = 'SELECT Id, API_Name__c, Object__r.API_Name__c, Durable_ID__c FROM Data_Dictionary_Field__c WHERE Data_Type__c = \'Picklist\' AND Status__c = \'' + ddCoreService.FIELD_STATUS_ACTIVE + '\' AND Object__r.Has_Record_Types__c = true ORDER BY API_Name__c';

        } else if (this.mode == 'field-permissions') {
            query = 'SELECT Id, API_Name__c, Object__r.API_Name__c, Durable_ID__c FROM Data_Dictionary_Field__c WHERE Data_Type__c = \'Picklist\' AND Status__c = \'' + ddCoreService.FIELD_STATUS_ACTIVE + '\' AND Object__r.Has_Record_Types__c = true ORDER BY API_Name__c';

        } else if (this.mode == 'dependencies') {
            query = 'SELECT Id, API_Name__c, Object__r.API_Name__c, Durable_ID__c FROM Data_Dictionary_Field__c WHERE Data_Type__c = \'Picklist\' AND Status__c = \'' + ddCoreService.FIELD_STATUS_ACTIVE + '\' AND Object__r.Has_Record_Types__c = true ORDER BY API_Name__c';
        } else {
            // Record counts
            query = 'SELECT Id, Data_Type__c, Data_Type_Details_Trunc__c, API_Name__c, Object__r.API_Name__c, Object__r.Has_Record_Types__c, Durable_ID__c, Usage_Count__c FROM Data_Dictionary_Field__c WHERE Status__c = \'' + ddCoreService.FIELD_STATUS_ACTIVE + '\' AND (Object__r.Type__c = \'' + ddCoreService.OBJECT_TYPE_STANDARDOBJECT + '\' OR Object__r.Type__c = \'' + ddCoreService.OBJECT_TYPE_CUSTOMOBJECT + '\') ORDER BY Name';
        }

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Data_Dictionary_Field__c> records) {
        ddFieldList fieldList = new ddFieldList(records);

        if (this.mode == 'recordcounts') {
            fieldList.setRecordCounts();
        }

        fieldList.Save();
    }

    public void finish(Database.BatchableContext bc) {


    }    

}