force-app/main/default/objects/Data_Dictionary_Field__c/Data_Dictionary_Field__c.object-meta.xml
<CustomObject>
    <description>Records of individual fields within standard and custom objects, custom settings, custom metadata, etc.</description>
    <label>Data Dictionary Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ddObjectTests.cls
@IsTest
public with sharing class ddObjectTests {

    @TestSetup
    private static void setupData() {
        ddObjectProcess ddo = new ddObjectProcess();
        ddo.execute();
    }

    @IsTest
    public static void testBatchCustomObject() {
        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object'));

        Test.startTest();
        ddObjectProcessBatch ddob = new ddObjectProcessBatch('Data_Dictionary_Field__c');
        Database.executeBatch(ddob, 1);
        Test.stopTest();

        // Assertions
        List<Data_Dictionary_Object__c> ddos = [SELECT Id, Durable_ID__c FROM Data_Dictionary_Object__c WHERE API_Name__c = 'Data_Dictionary_Field__c'];
        System.assertEquals(1, ddos.size());

    }

    @IsTest
    public static void testBatchStandardObject() {
        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object'));

        Test.startTest();
        ddObjectProcessBatch ddob = new ddObjectProcessBatch('Contact');
        Database.executeBatch(ddob, 1);
        Test.stopTest();

        // TODO: asserts!
    }

    @IsTest
    public static void testBatchCustomObjectFieldBasics() {
        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields'));

        Data_Dictionary_Object__c ddo = [SELECT Id, Durable_ID__c FROM Data_Dictionary_Object__c WHERE API_Name__c = 'Data_Dictionary_Field__c' LIMIT 1];

        ddObject ddoToProcess = new ddObject(ddo.Id, ddo.Durable_ID__c);
        ddoToProcess.Fill();
        ddoToProcess.Save();

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch('Data_Dictionary_Field__c', 'only-basics');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // TODO: asserts!
    }

    @IsTest
    public static void testBatchCustomObjectFieldLayouts() {
        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields'));

        ddObjectFields ddf = new ddObjectFields();
        ddf.SetObjectId(ddo.Id);
        ddf.SetObjectDurableId(ddo.Durable_ID__c);
        ddf.SetObjectAPIName(ddo.API_Name__c);

        ddf.fillFromDDFs();
        ddf.fillFromFieldDefs();
        ddf.updateFieldMap();
        ddf.fillFromDescribe();

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch('Data_Dictionary_Field__c', 'only-page-layouts');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // TODO: asserts!
    }

}