force-app/main/default/objects/Data_Dictionary_Field__c/Data_Dictionary_Field__c.object-meta.xml
<CustomObject>
    <description>Records of individual fields within standard and custom objects, custom settings, custom metadata, etc.</description>
    <label>Data Dictionary Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Data_Dictionary_Object__c</referenceTo>
    <relationshipLabel>Data Dictionary Fields</relationshipLabel>
    <relationshipName>Data_Dictionary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Field</fullName>
            </value>
            <value>
                <fullName>Standard Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description of this object; 1000 character limit.</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Stub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Object</fullName>
            </value>
            <value>
                <fullName>Custom Object</fullName>
            </value>
            <value>
                <fullName>Custom Metadata Type</fullName>
            </value>
            <value>
                <fullName>Custom Setting</fullName>
            </value>
            <value>
                <fullName>Big Object</fullName>
            </value>
            <value>
                <fullName>Platform Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ddObjectFieldTests.cls
@IsTest
public with sharing class ddObjectFieldTests {



    @IsTest
    public static void testBatchCustomObjectFieldBasics() {
        ddObjectProcess ddop = new ddObjectProcess();
        ddop.execute();

        Data_Dictionary_Object__c ddo = [SELECT Id, Durable_ID__c FROM Data_Dictionary_Object__c WHERE API_Name__c = 'Data_Dictionary_Field__c' LIMIT 1];

        List<FieldDefinition> fieldDefinitions = [
            SELECT Id, DurableId, QualifiedApiName
            FROM FieldDefinition
            WHERE EntityDefinition.DurableId = :ddo.Durable_ID__c
            AND QualifiedApiName = 'Description__c'
        ];

        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields', fieldDefinitions[0].DurableId));

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch(ddo.Durable_ID__c, 'only-basics');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // Assertions


    }


    @IsTest
    public static void testBatchCustomObjectFieldActiveBasics() {
        List<EntityDefinition> entityData = [
            SELECT DurableId, QualifiedApiName
            FROM EntityDefinition
            WHERE QualifiedApiName = 'Data_Dictionary_Field__c'
        ];

        Data_Dictionary_Object__c ddo = new Data_Dictionary_Object__c();
        ddo.API_Name__c = 'Data_Dictionary_Field__c';
        ddo.Name = 'Data Dictionary Field';
        ddo.Status__c = ddCoreService.OBJECT_STATUS_ACTIVE;
        ddo.Type__c = ddCoreService.OBJECT_TYPE_CUSTOMOBJECT;
        ddo.Durable_ID__c = entityData[0].DurableId;

        insert ddo;

        List<FieldDefinition> fieldDefinitions = [
            SELECT Id, DurableId, QualifiedApiName
            FROM FieldDefinition
            WHERE EntityDefinition.DurableId = :ddo.Durable_ID__c
            AND QualifiedApiName = 'Description__c'
        ];

        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields', fieldDefinitions[0].DurableId));

        /*
        ddObjectFields ddf = new ddObjectFields();
        ddf.setObjectId(ddo.Id);
        ddf.setObjectDurableId(ddo.Durable_ID__c);
        ddf.setObjectAPIName(ddo.API_Name__c);

        ddf.fillFromDDFs();
        ddf.fillFromFieldDefs();
        ddf.updateFieldMap();
        ddf.fillFromDescribe();
        ddf.fillCreateDates();
        ddf.fillOwnership();

        ddf.save();
        */

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch(ddo.Durable_ID__c, 'only-basics');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // TODO: asserts!
    }

    @IsTest
    public static void testBatchCustomObjectFieldLayouts() {
        List<EntityDefinition> entityData = [
            SELECT DurableId, QualifiedApiName
            FROM EntityDefinition
            WHERE QualifiedApiName = 'Data_Dictionary_Field__c'
        ];

        Data_Dictionary_Object__c ddo = new Data_Dictionary_Object__c();
        ddo.API_Name__c = 'Data_Dictionary_Field__c';
        ddo.Name = 'Data Dictionary Field';
        ddo.Status__c = ddCoreService.OBJECT_STATUS_ACTIVE;
        ddo.Type__c = ddCoreService.OBJECT_TYPE_CUSTOMOBJECT;
        ddo.Durable_ID__c = entityData[0].DurableId;

        insert ddo;

        List<FieldDefinition> fieldDefinitions = [
            SELECT Id, DurableId, QualifiedApiName
            FROM FieldDefinition
            WHERE EntityDefinition.DurableId = :ddo.Durable_ID__c
            AND QualifiedApiName = 'Description__c'
        ];

        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields', fieldDefinitions[0].DurableId));

        ddObjectFields ddf = new ddObjectFields();
        ddf.setObjectId(ddo.Id);
        ddf.setObjectDurableId(ddo.Durable_ID__c);
        ddf.setObjectAPIName(ddo.API_Name__c);

        ddf.fillFromDDFs();
        ddf.fillFromFieldDefs();
        ddf.updateFieldMap();
        ddf.fillFromDescribe();
        ddf.save();

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch(ddo.Durable_ID__c, 'only-page-layouts');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // TODO: asserts!
    }

    @IsTest
    public static void testBatchCustomObjectFieldPerms() {
        List<EntityDefinition> entityData = [
            SELECT DurableId, QualifiedApiName
            FROM EntityDefinition
            WHERE QualifiedApiName = 'Data_Dictionary_Field__c'
        ];

        Data_Dictionary_Object__c ddo = new Data_Dictionary_Object__c();
        ddo.API_Name__c = 'Data_Dictionary_Field__c';
        ddo.Name = 'Data Dictionary Field';
        ddo.Status__c = ddCoreService.OBJECT_STATUS_ACTIVE;
        ddo.Type__c = ddCoreService.OBJECT_TYPE_CUSTOMOBJECT;
        ddo.Durable_ID__c = entityData[0].DurableId;

        insert ddo;

        List<FieldDefinition> fieldDefinitions = [
            SELECT Id, DurableId, QualifiedApiName
            FROM FieldDefinition
            WHERE EntityDefinition.DurableId = :ddo.Durable_ID__c
            AND QualifiedApiName = 'Description__c'
        ];

        Test.setMock(HttpCalloutMock.class, new ddHttpMockResponse('object-fields', fieldDefinitions[0].DurableId));

        ddObjectFields ddf = new ddObjectFields();
        ddf.setObjectId(ddo.Id);
        ddf.setObjectDurableId(ddo.Durable_ID__c);
        ddf.setObjectAPIName(ddo.API_Name__c);

        ddf.fillFromDDFs();
        ddf.fillFromFieldDefs();
        ddf.updateFieldMap();
        ddf.fillFromDescribe();
        ddf.save();

        List<Data_Dictionary_Field__c> fieldList = [SELECT Id FROM Data_Dictionary_Field__c where Object__c = :ddo.Id];
        System.debug(fieldList.size());

        Test.startTest();
        ddFieldProcessBatch ddfp = new ddFieldProcessBatch(ddo.Durable_ID__c, 'only-permissions');
        Database.executeBatch(ddfp, 1);
        Test.stopTest();

        // TODO: asserts!
    }

}