force-app/main/default/objects/Data_Dictionary_Field__c/Data_Dictionary_Field__c.object-meta.xml
<CustomObject>
    <description>Records of individual fields within standard and custom objects, custom settings, custom metadata, etc.</description>
    <label>Data Dictionary Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Is_Dependent_Picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Auto Number</fullName>
            </value>
            <value>
                <fullName>BitVector</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Complex Value</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>External Lookup</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Hierarchy</fullName>
            </value>
            <value>
                <fullName>IP Address</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Master-Detail</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
            </value>
            <value>
                <fullName>Roll-Up Summary</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Data_Type_Details_Trunc__c.field-meta.xml
<CustomField>
    <fullName>Data_Type_Details_Trunc__c</fullName>
    <inlineHelpText>In a few cases, Data Type Details can be very long. This is a shortened (truncated) version, limited to 100 characters, for use in filtering.</inlineHelpText>
    <label>Data Type Details (Trunc)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Data_Dictionary_Object__c</referenceTo>
    <relationshipLabel>Data Dictionary Fields</relationshipLabel>
    <relationshipName>Data_Dictionary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Field__c/fields/Usage_Count__c.field-meta.xml
<CustomField>
    <fullName>Usage_Count__c</fullName>
    <inlineHelpText>A count of how many records have a value (are not empty/null) for this field, as of the last sync. Note that this information can&apos;t be obtained for certain types of fields--for example, a formula field can theoretically have or not have a value depending on the user viewing the record.</inlineHelpText>
    <label>Usage Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Has_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Has_Record_Types__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the object uses Record Types.</inlineHelpText>
    <label>Has Record Types</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ddFieldList.cls
public with sharing class ddFieldList {

    private List<Data_Dictionary_Field__c> fieldList;

    public ddFieldList(List<Data_Dictionary_Field__c> fieldList) {
        this.fieldList = fieldList;
    }


    public Boolean setRecordCounts() {
        for (Data_Dictionary_Field__c ddf : records) {
            Integer totalUsage = null;
            Map<Id, Integer> usageMapById = new Map<Id, Integer>();

            if (ddf.Object__r.Has_Record_Types__c) {
                if (ddCoreService.FIELD_TYPES_COUNTABLE.contains(ddf.Data_Type__c) && ddCoreService.FIELD_TRUNCTYPES_PSEUDOCOUNTABLE.contains(ddf.Data_Type_Details_Trunc__c) == false) {
                    totalUsage = 0;
                    try {
                        List<AggregateResult> groupedResults = Database.query('SELECT RecordTypeId, Count(' + ddf.API_Name__c + ') FROM ' + ddf.Object__r.API_Name__c + ' GROUP BY RecordTypeId');

                        for (AggregateResult ar : groupedResults) {
                            usageMapById.put((Id)ar.get('RecordTypeId'), (Integer)ar.get('expr0'));
                            totalUsage = totalUsage + (Integer)ar.get('expr0');
                        }
                    } catch (Exception ex) {
                        System.debug('Error in record type COUNT(fieldName) query for field ' + ddf.API_Name__c);
                        throw ex;
                    }
                } else {
                    totalUsage = 0;
                }
            } else {
                if (ddf.API_Name__c != 'Id' && (ddCoreService.FIELD_TYPES_COUNTABLE.contains(ddf.Data_Type__c) || ddCoreService.FIELD_TRUNCTYPES_PSEUDOCOUNTABLE.contains(ddf.Data_Type_Details_Trunc__c))) {
                    totalUsage = 0;
                    try {
                        // List<AggregateResult> groupedResults = Database.query('SELECT Count(' + ddf.API_Name__c + ') FROM ' + ddf.Object__r.API_Name__c);
                        List<AggregateResult> groupedResults = Database.query('SELECT Count(Id) FROM ' + ddf.Object__r.API_Name__c + ' WHERE ' + ddf.API_Name__c + ' != null');

                        for (AggregateResult ar : groupedResults) {
                            totalUsage = totalUsage + (Integer)ar.get('expr0');
                        }
                    } catch (Exception ex) {
                        System.debug('Error in COUNT(Id) query for field ' + ddf.API_Name__c);
                        throw ex;
                    }
                }
            }

            ddf.Usage_Count__c = totalUsage;

            // Calculate usage by record type
        }
    }


    public String Save() {
        try {
            upsert this.fieldList;
            return 'success';
        } catch (Exception ex) {
            return ex.getMessage();
        }
    }


}