force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Stub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ddObjectProcessBatch.cls
public with sharing class ddObjectProcessBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {

    // Setting an API Name will process just that object; otherwise all objects will be processed
    private String apiName;

    public ddObjectProcessBatch(String apiName) {
        this.apiName = apiName;
    }

    public ddObjectProcessBatch() {
        this.apiName = null;
    }

    public List<SObject> start(Database.BatchableContext bc) {
        if (String.isNotEmpty(this.apiName)) {
            return [
                SELECT Id, Durable_ID__c
                FROM Data_Dictionary_Object__c
                WHERE API_Name__c = :this.apiName
                LIMIT 1];
        } else {
            return [
                SELECT Id, Durable_ID__c
                FROM Data_Dictionary_Object__c
                WHERE Status__c != :ddCoreService.OBJECT_STATUS_DELETED
                ORDER BY Name];
        }
    }

    public void execute(Database.BatchableContext bc, List<Data_Dictionary_Object__c> records) {
        for (Data_Dictionary_Object__c ddo : records) {
            ddObject ddoToProcess = new ddObject(ddo.Id, ddo.Durable_ID__c);
            ddoToProcess.Fill();
            ddoToProcess.Save();
        }
    }

    public void finish(Database.BatchableContext bc) {
        if (Test.isRunningTest() == false) {
            ddFieldProcessBatch ddfb = new ddFieldProcessBatch(this.apiName, 'only-basics');
            Database.executeBatch(ddfb, 1);
        }
    }

}