force-app/main/default/objects/Data_Dictionary_Object__c/Data_Dictionary_Object__c.object-meta.xml
<CustomObject>
    <description>Represents standard and custom objects, custom settings, metadata, and platform events.</description>
    <label>Data Dictionary Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Dictionary Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Data_Dictionary_Object__c/fields/Durable_ID__c.field-meta.xml
<CustomField>
    <fullName>Durable_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Durable ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ddFieldProcessBatch.cls
public with sharing class ddFieldProcessBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Durable_ID__c, API_Name__c FROM Data_Dictionary_Object__c ORDER BY Name';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Data_Dictionary_Object__c> records) {
        for (Data_Dictionary_Object__c ddo : records) {
            // ddFieldService.processObjectByDDIds(ddo.Id, ddo.Durable_ID__c);
            ddObjectFields ddf = new ddObjectFields();
            ddf.SetObjectId(ddo.Id);
            ddf.SetObjectDurableId(ddo.Durable_ID__c);
            ddf.SetObjectAPIName(ddo.API_Name__c);
            ddf.Fill();
            ddf.Save();
        }
    }

    public void finish(Database.BatchableContext bc) {
        // TODO: determine if we fire off this batch, and the appropriate batch size, based on metadata
        //ddFieldDetailsBatch ddfb = new ddFieldDetailsBatch();
        //Database.executeBatch(ddfb, 10);
    }

}